services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /Users/isen0011/Documents/Postgres/ccf_mcp:/var/lib/postgresql/data
  api:
    logging:
      options:
        max-size: 50m
    build: '.'
    environment:
      DB_HOST: db
      DB_NAME: myappdb
      DB_USERNAME: my_user
      DB_PASSWORD: a123
      SELENIUM_DRIVER_URL: "http://selenium:4444/wd/hub"
    env_file: ".env"
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - '.:/app'
    entrypoint: ["script/_entrypoint.sh"]
    command: >
      bash -c ' RAILS_ENV=development bin/rails s -b ssl://0.0.0.0'
