services:
  api:
    logging:
      options:
        max-size: 50m
    build: '.'
    env_file: ".env"
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - '.:/app'
    entrypoint: ["script/_entrypoint.sh"]
    command: >
      bash -c ' RAILS_ENV=development bin/rails s -b ssl://0.0.0.0'
